apiVersion: apps/v1
kind: Deployment
metadata:
  name: noteservice-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: noteservice
    environment: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: noteservice
      environment: {{ .Values.namespace }}
  template:
    metadata:
      labels:
        app: noteservice
        environment: {{ .Values.namespace }}
    spec:
      nodeSelector: 
        {{ toYaml .Values.nodeSelector | indent 8 }}
      containers:
        - name: noteservice
          image: "{{ .Values.notesService.image.repository }}:{{ .Values.notesService.image.tag }}"
          imagePullPolicy: {{ .Values.notesService.image.pullPolicy }}
          ports:
            - containerPort: 8002
          envFrom:
            - secretRef:
                name: app-secrets         
          volumeMounts:
            - name: mysql-ssl-cert-volume
              mountPath: /app/ssl
              readOnly: true
      volumes:
        - name: mysql-ssl-cert-volume
          secret:
            secretName: mysql-ssl-cert # Name of the secret containing the certificate
            items:
              - key: DigiCertGlobalRootCA.crt.pem
                path: DigiCertGlobalRootCA.crt.pem  
       

---
apiVersion: v1
kind: Service
metadata:
  name: notes-service
  namespace: {{ .Values.namespace }}
  labels:
    app: noteservice
    environment: {{ .Values.namespace }}
spec:
  selector:
    app: noteservice
    environment: {{ .Values.namespace }}
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8002
  type: ClusterIP                  

