apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  DATABASE_URL: "{{ .Values.secret.databaseUrl }}"
  SECRET_KEY: "{{ .Values.secret.secretKey }}"
data:
  DigiCertGlobalRootCA.crt.pem: {{ .Files.Get "certs/DigiCertGlobalRootCA.crt.pem" | b64enc }}