# roles/ingress/tasks/main.yml
---
- name: Create ingress-nginx namespace
  kubernetes.core.k8s:
    name: ingress-nginx
    api_version: v1
    kind: Namespace
    state: present

- name: Add ingress-nginx repository
  kubernetes.core.helm_repository:
    name: ingress-nginx
    repo_url: https://kubernetes.github.io/ingress-nginx

- name: Install or upgrade ingress-nginx Helm chart
  kubernetes.core.helm:
    name: ingress-nginx
    chart_ref: ingress-nginx/ingress-nginx
    release_namespace: ingress-nginx
    create_namespace: true
    wait: true
    values:
      controller:
        service:
          annotations:
            service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: /healthz