apiVersion: v1
kind: Secret
metadata:
  name: secret
  namespace: staging
type: Opaque
stringData:
    DATABASE_URL: mysql+mysqlconnector://kpadmin:p1Kistan0978^@python-dbserver.mysql.database.azure.com:3306/pyth-micros-db?ssl_ca=/app/ssl/DigiCertGlobalRootCA.crt.pem
    SECRET_KEY: J8j5mP3qRvS9tXwZy2K6Nc4Lb7V1G0xDh
