- name: Install or upgrade ingress-nginx
  command: >
    helm upgrade --install ingress-nginx ingress-nginx/ingress-nginx
    --namespace ingress-nginx
    --create-namespace
    --set controller.service.annotations.service\.beta\.kubernetes\.io/azure-load-balancer-health-probe-request-path=/healthz
    --set controller.service.externalTrafficPolicy=Local
    --set controller.service.annotations.service\.beta\.kubernetes\.io/azure-load-balancer-internal=false
  environment:
    KUBECONFIG: "{{ lookup('env', 'KUBECONFIG') }}"
