apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-keyvault-secrets
  namespace: {{ .Values.namespace }} 
spec:
  provider: azure
  secretObjects:
    - secretName: app-secrets
      type: Opaque
      data:
        - objectName: DATABASE-URL
          key: DATABASE_URL
        - objectName: SECRET-KEY
          key: SECRET_KEY
  parameters:
    usePodIdentity: "false"
    keyvaultName: "{{ .Values.keyvault.name }}"
    objects: |
      array:
        - |
          objectName: DATABASE-URL
          objectType: secret
        - |
          objectName: SECRET-KEY
          objectType: secret
    tenantId: "{{ .Values.keyvault.tenantId }}"
